server:
  port: 9800

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/2020simple?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT&useSSL=false
    username: root
    password: root
